### ISSUE TITLE
Release 0.26.0 out on pypi

### ISSUE THREAD

**Issue by megies** [conda-forge/m2crypto-feedstock#15]
Just wanted to drop a note that a new release is out on pypi, in case anybody is maintaining this feedstock: https://pypi.python.org/pypi/M2Crypto/0.26.0

It's not vital for me, just wanted to let you know..

CC @barsch

**Comment by jakirkham** [comment]
Feel free to do a PR if you are interested.

**Comment by jakirkham** [comment]
As it's now at 0.31.0 ( https://github.com/conda-forge/m2crypto-feedstock/pull/24 ), going to close this out. If that version is needed, it can be added in a legacy branch.
