### ISSUE TITLE
UnsatisfiableError while installing m2crypto python 3.6 linux

### ISSUE THREAD

**Issue by JuanManuelFigueroa** [conda-forge/m2crypto-feedstock#23]
Issue:

I am getting the error while trying to install m2crypto using python 3.6 on a linux environment.
Error details:
```bash
UnsatisfiableError: The following specifications were found to be in conflict:
   - m2crypto -> distribute -> python=2.6
   - python=3.6
```

Environment details (`environment.yml`)
```bash
name: test
channels:
- conda-forge
dependencies:
- python==3.6
- m2crypto
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by megies** [comment]
Strange, linux builds seemed fine in #24 but after merging that PR, the linux builds failed on master, that's why there are no Linux packages. I think #24 needs to be retriggered with a plain build number bump to try again?

**Comment by megies** [comment]
See #25

**Comment by jakirkham** [comment]
Could you please recheck and let us know if this is still an issue, @JuanManuelFigueroa?

**Comment by megies** [comment]
Installation is fine for me now, thanks @jakirkham 

CC @JuanManuelFigueroa
